class_name Enum extends Node

enum ELEMENT { PHYSICAL = 1, ARCANE = 2, FIRE = 4, FROST = 8, LIGHTNING = 16, POISON = 32, ACID = 64, HOLY = 128, SHADOW = 256, DIVINE = 512, ELDRICH = 1024}

enum DAMAGE_TYPE { MELEE, RANGE, SPELL, HEALING }

enum FACTION { PLAYER, ENEMY, NEUTRAL, PASSIVE }

enum INVENTORY_SLOT { NONE, HEAD, ARMOR, BOOTS, GLOVES, RING, AMULET, ONEHAND, TWOHAND, OFFHAND }

enum EFFECT_TYPE { NONE, ACTIVE, PASSIVE }
enum SPELL_TARGET { NONE, SELF, FRIENDLY, ENEMY, NOVA, GRID, GLOBAL }
enum SPELL_SCALING { ATTACKPOWER, SPELLPOWER, WEAPON }
